import { Hono } from 'hono';
import { Env, SQLRequest } from '../models/types';
import { SchemaSQLValidator, DataSQLValidator } from '../services/validator.service';
import { DatabaseService, DatabaseError } from '../services/database.service';
import { getAppConfig } from '../config/env';
import { sendSuccess, sendError } from '../utils/response';
import { AppContext } from '../types/auth';
import { requireAuth } from '../middleware/auth.middleware';
import { requirePermission } from '../middleware/authorization.middleware';

const adminRouter = new Hono<AppContext>();

// Enforce JWT authentication on all admin endpoints
adminRouter.use('*', requireAuth);

/**
 * POST /admin/create-schema
 * Receives DDL SQL (CREATE/ALTER) generated by LLM, validates, and runs it on Postgres.
 */
adminRouter.post('/create-schema', requirePermission('CREATE_SCHEMA'), async (c) => {
  const startTime = performance.now();
  console.log(`[API CALL] POST /admin/create-schema - Start`);

  try {
    const body = await c.req.json<SQLRequest>().catch(() => null);

    if (!body || !body.sql) {
      console.warn(`[VALIDATION ERROR] POST /admin/create-schema - Missing SQL in request body`);
      return sendError(c, 400, 'Invalid Request: SQL statement is required in request body');
    }

    const sqlQuery = body.sql;
    console.log(`[LOG] SQL received for admin validation:\n${sqlQuery}`);

    // Validate DDL SQL query
    const validation = SchemaSQLValidator.validate(sqlQuery);
    if (!validation.isValid) {
      console.warn(`[VALIDATION ERROR] POST /admin/create-schema - Blocked SQL: ${validation.reason}`);
      return sendError(c, 400, 'Invalid SQL: Command rejected by validator rules', validation.reason);
    }

    // Connect to database
    const config = getAppConfig(c.env);
    const dbService = new DatabaseService(config.databaseUrl);

    // Execute schema modification SQL
    console.log(`[LOG] Executing admin SQL on Neon database...`);
    const dbResult = await dbService.execute(sqlQuery);

    const executionTimeMs = parseFloat((performance.now() - startTime).toFixed(2));
    console.log(`[SUCCESS] POST /admin/create-schema - Execution time: ${executionTimeMs}ms`);

    return sendSuccess(
      c,
      { affectedRows: dbResult.rowCount },
      'Schema operation executed successfully',
      executionTimeMs
    );
  } catch (error: any) {
    const executionTimeMs = parseFloat((performance.now() - startTime).toFixed(2));
    console.error(`[FAILURE] POST /admin/create-schema - Execution time: ${executionTimeMs}ms - Error:`, error);
    
    const isDbError = error instanceof DatabaseError;
    const statusCode = isDbError ? 400 : 500;
    const clientMessage = isDbError
      ? 'Database operation failed'
      : 'Internal Server Error or Database failure during execution';

    return sendError(
      c,
      statusCode,
      clientMessage,
      error.message || String(error)
    );
  }
});

/**
 * POST /admin/insert-data
 * Receives DML SQL (INSERT/UPDATE/DELETE) generated by LLM, validates, and runs it on Postgres.
 */
adminRouter.post('/insert-data', requirePermission('INSERT_DATA'), async (c) => {
  const startTime = performance.now();
  console.log(`[API CALL] POST /admin/insert-data - Start`);

  try {
    const body = await c.req.json<SQLRequest>().catch(() => null);

    if (!body || !body.sql) {
      console.warn(`[VALIDATION ERROR] POST /admin/insert-data - Missing SQL in request body`);
      return sendError(c, 400, 'Invalid Request: SQL statement is required in request body');
    }

    const sqlQuery = body.sql;
    console.log(`[LOG] SQL received for admin data validation:\n${sqlQuery}`);

    // Validate DML SQL query
    const validation = DataSQLValidator.validate(sqlQuery);
    if (!validation.isValid) {
      console.warn(`[VALIDATION ERROR] POST /admin/insert-data - Blocked SQL: ${validation.reason}`);
      return sendError(c, 400, 'Invalid SQL: Command rejected by validator rules', validation.reason);
    }

    // Connect to database
    const config = getAppConfig(c.env);
    const dbService = new DatabaseService(config.databaseUrl);

    // Execute data initialization SQL
    console.log(`[LOG] Executing admin data SQL on Neon database...`);
    const dbResult = await dbService.execute(sqlQuery);

    const executionTimeMs = parseFloat((performance.now() - startTime).toFixed(2));
    console.log(`[SUCCESS] POST /admin/insert-data - Execution time: ${executionTimeMs}ms`);

    return sendSuccess(
      c,
      { affectedRows: dbResult.rowCount },
      'Data operation executed successfully',
      executionTimeMs
    );
  } catch (error: any) {
    const executionTimeMs = parseFloat((performance.now() - startTime).toFixed(2));
    console.error(`[FAILURE] POST /admin/insert-data - Execution time: ${executionTimeMs}ms - Error:`, error);
    
    const isDbError = error instanceof DatabaseError;
    const statusCode = isDbError ? 400 : 500;
    const clientMessage = isDbError
      ? 'Database operation failed'
      : 'Internal Server Error or Database failure during execution';

    return sendError(
      c,
      statusCode,
      clientMessage,
      error.message || String(error)
    );
  }
});

export default adminRouter;
