import { Hono } from 'hono';
import { Env, SQLRequest } from '../models/types';
import { SchemaSQLValidator, DataSQLValidator } from '../services/validator.service';
import { DatabaseService, DatabaseError } from '../services/database.service';
import { KnowledgeService } from '../services/KnowledgeService';
import { getAppConfig } from '../config/env';
import { sendSuccess, sendError } from '../utils/response';
import { PromptService, PromptType } from '../services/PromptService';
import { GeminiService } from '../services/GeminiService';
import { AppContext } from '../types/auth';
import { requireAuth } from '../middleware/auth.middleware';
import { requirePermission } from '../middleware/authorization.middleware';

const adminRouter = new Hono<AppContext>();

// Enforce JWT authentication on all admin endpoints
adminRouter.use('*', requireAuth);

/**
 * POST /admin/create-schema
 * Receives DDL SQL (CREATE/ALTER) generated by LLM, validates, and runs it on Postgres.
 */
adminRouter.post('/create-schema', requirePermission('CREATE_SCHEMA'), async (c) => {
  const startTime = performance.now();
  console.log(`[API CALL] POST /admin/create-schema - Start`);

  try {
    const body = await c.req.json<SQLRequest>().catch(() => null);

    if (!body || (!body.sql && !body.prompt)) {
      console.warn(`[VALIDATION ERROR] POST /admin/create-schema - Missing SQL or prompt in request body`);
      return sendError(c, 400, 'Invalid Request: SQL statement or prompt is required in request body');
    }

    const config = getAppConfig(c.env);
    const dbService = new DatabaseService(config.databaseUrl);
    let sqlQuery = '';

    if (body.prompt) {
      console.log(`[LOG] Prompt received for schema generation: ${body.prompt}`);
      if (!config.geminiApiKey) {
        return sendError(c, 500, 'Configuration Error: GEMINI_API_KEY is not configured on the backend.');
      }
      
      const promptService = new PromptService();
      const geminiService = new GeminiService(config.geminiApiKey, promptService);

      const context = `Database Complexity: High\nBusiness Description: AI-Powered Application Database\nTarget Database: PostgreSQL`;
      const geminiResponse = await geminiService.generate(
        PromptType.DATABASE_GENERATION,
        body.prompt,
        context
      );

      try {
        const parsed = JSON.parse(geminiResponse);
        sqlQuery = parsed.sql || geminiResponse;
      } catch (err) {
        sqlQuery = geminiResponse;
      }
    } else {
      sqlQuery = body.sql!;
    }

    console.log(`[LOG] SQL received for admin validation:\n${sqlQuery}`);

    // Validate DDL SQL query
    let validation = SchemaSQLValidator.validate(sqlQuery);
    if (!validation.isValid) {
      if (body.prompt && config.geminiApiKey) {
        console.log(`[LOG] Schema validation failed. Attempting auto-correction using sql_validation...`);
        const promptService = new PromptService();
        const geminiService = new GeminiService(config.geminiApiKey, promptService);
        
        const context = `Generated SQL:\n${sqlQuery}\n\nValidation Failure Reason:\n${validation.reason}`;
        try {
          const correctionResponse = await geminiService.generate(
            PromptType.SQL_VALIDATION,
            'Please correct the generated DDL SQL to make it comply with validation rules.',
            context
          );
          
          let correctedSql = '';
          try {
            const parsed = JSON.parse(correctionResponse);
            correctedSql = parsed.sql || correctionResponse;
          } catch (err) {
            correctedSql = correctionResponse;
          }

          const reValidation = SchemaSQLValidator.validate(correctedSql);
          if (reValidation.isValid) {
            console.log(`[LOG] Auto-correction successful!`);
            sqlQuery = correctedSql;
            validation = reValidation;
          } else {
            console.warn(`[VALIDATION ERROR] Auto-correction SQL still invalid: ${reValidation.reason}`);
            return sendError(c, 400, 'Invalid SQL: Auto-correction failed validator rules', reValidation.reason);
          }
        } catch (corrErr: any) {
          console.error(`[LOG] Error during SQL validation auto-correction:`, corrErr);
          return sendError(c, 400, 'Invalid SQL: Command rejected by validator rules', validation.reason);
        }
      } else {
        console.warn(`[VALIDATION ERROR] POST /admin/create-schema - Blocked SQL: ${validation.reason}`);
        return sendError(c, 400, 'Invalid SQL: Command rejected by validator rules', validation.reason);
      }
    }

    // Execute schema modification SQL
    console.log(`[LOG] Executing admin SQL on Neon database...`);
    const dbResult = await dbService.execute(sqlQuery);

    // Trigger Diagram Metadata generation and caching
    try {
      console.log(`[LOG] Schema execution successful. Generating diagram metadata...`);
      const schemaSummary = await dbService.getSchemaSummary();
      
      let diagramGenerated = false;

      if (config.geminiApiKey) {
        try {
          const promptService = new PromptService();
          const geminiService = new GeminiService(config.geminiApiKey, promptService);
          const geminiResponse = await geminiService.generate(
            PromptType.DIAGRAM_GENERATION,
            'Please generate the database ERD diagram JSON representation.',
            schemaSummary
          );

          const parsed = JSON.parse(geminiResponse);
          if (parsed && parsed.tables && parsed.relationships && parsed.layoutHints) {
            await dbService.saveDiagramData(
              parsed.mermaid || '',
              parsed.tables,
              parsed.relationships,
              parsed.layoutHints,
              parsed.labels || [],
              parsed.groups || []
            );
            console.log(`[SUCCESS] Cached diagram metadata via Gemini.`);
            diagramGenerated = true;
          }
        } catch (geminiErr) {
          console.warn(`[Diagram Cache Warning] Gemini diagram generation failed, falling back to programmatic metadata:`, geminiErr);
        }
      }

      if (!diagramGenerated) {
        // Programmatic fallback
        console.log(`[LOG] Executing programmatic fallback for diagram generation...`);
        const structure = await dbService.getSchemaStructure();
        
        const tables = structure.tables.map((t: any) => ({
          name: t.name,
          label: t.name.charAt(0).toUpperCase() + t.name.slice(1) + ' Table',
          columns: t.columns.map((c: any) => ({
            name: c.name,
            type: c.type,
            isPrimaryKey: c.isPrimaryKey,
            isForeignKey: c.isForeignKey
          }))
        }));

        const relationships: any[] = [];
        structure.tables.forEach((t: any) => {
          t.columns.forEach((c: any) => {
            if (c.isForeignKey && c.foreignKeyRef) {
              relationships.push({
                sourceTable: t.name,
                sourceColumn: c.name,
                targetTable: c.foreignKeyRef.table,
                targetColumn: c.foreignKeyRef.column,
                label: 'references'
              });
            }
          });
        });

        const layoutHints: Record<string, { x: number; y: number }> = {};
        tables.forEach((t: any, idx: number) => {
          const col = idx % 3;
          const row = Math.floor(idx / 3);
          layoutHints[t.name] = { x: col * 380 + 50, y: row * 320 + 50 };
        });

        const groups = [{
          id: 'general',
          name: 'General Schema',
          tables: tables.map((t: any) => t.name)
        }];

        const labels = [{
          text: 'Database System Canvas',
          x: 50,
          y: 20
        }];

        const relStrings = relationships.map(r => `  "${r.sourceTable}" }o--|| "${r.targetTable}" : "${r.label}"`);
        const mermaid = `erDiagram\n` + relStrings.join('\n');

        await dbService.saveDiagramData(mermaid, tables, relationships, layoutHints, labels, groups);
        console.log(`[SUCCESS] Programmatic fallback diagram metadata cached successfully.`);
      }
    } catch (diagErr: any) {
      console.error(`[Diagram Cache Error] Failed to generate or save diagram metadata:`, diagErr);
    }

    // Trigger Knowledge Center documentation and artifacts generation
    try {
      console.log(`[LOG] Schema creation successful. Triggering Knowledge Center documentation pipeline...`);
      await KnowledgeService.generateAllKnowledge(dbService, config.geminiApiKey || '');
    } catch (knowErr: any) {
      console.error(`[Knowledge Generation Error] Failed to generate database documentation artifacts:`, knowErr);
    }

    const executionTimeMs = parseFloat((performance.now() - startTime).toFixed(2));
    console.log(`[SUCCESS] POST /admin/create-schema - Execution time: ${executionTimeMs}ms`);

    return sendSuccess(
      c,
      { affectedRows: dbResult.rowCount },
      'Schema operation executed successfully',
      executionTimeMs
    );
  } catch (error: any) {
    const executionTimeMs = parseFloat((performance.now() - startTime).toFixed(2));
    console.error(`[FAILURE] POST /admin/create-schema - Execution time: ${executionTimeMs}ms - Error:`, error);
    
    const isDbError = error instanceof DatabaseError;
    const statusCode = isDbError ? 400 : 500;
    const clientMessage = isDbError
      ? 'Database operation failed'
      : 'Internal Server Error or Database failure during execution';

    return sendError(
      c,
      statusCode,
      clientMessage,
      error.message || String(error)
    );
  }
});

/**
 * POST /admin/insert-data
 * Receives DML SQL (INSERT/UPDATE/DELETE) generated by LLM, validates, and runs it on Postgres.
 */
adminRouter.post('/insert-data', requirePermission('INSERT_DATA'), async (c) => {
  const startTime = performance.now();
  console.log(`[API CALL] POST /admin/insert-data - Start`);

  try {
    const body = await c.req.json<SQLRequest>().catch(() => null);

    if (!body || !body.sql) {
      console.warn(`[VALIDATION ERROR] POST /admin/insert-data - Missing SQL in request body`);
      return sendError(c, 400, 'Invalid Request: SQL statement is required in request body');
    }

    const sqlQuery = body.sql;
    console.log(`[LOG] SQL received for admin data validation:\n${sqlQuery}`);

    // Validate DML SQL query
    const validation = DataSQLValidator.validate(sqlQuery);
    if (!validation.isValid) {
      console.warn(`[VALIDATION ERROR] POST /admin/insert-data - Blocked SQL: ${validation.reason}`);
      return sendError(c, 400, 'Invalid SQL: Command rejected by validator rules', validation.reason);
    }

    // Connect to database
    const config = getAppConfig(c.env);
    const dbService = new DatabaseService(config.databaseUrl);

    // Execute data initialization SQL
    console.log(`[LOG] Executing admin data SQL on Neon database...`);
    const dbResult = await dbService.execute(sqlQuery);

    const executionTimeMs = parseFloat((performance.now() - startTime).toFixed(2));
    console.log(`[SUCCESS] POST /admin/insert-data - Execution time: ${executionTimeMs}ms`);

    return sendSuccess(
      c,
      { affectedRows: dbResult.rowCount },
      'Data operation executed successfully',
      executionTimeMs
    );
  } catch (error: any) {
    const executionTimeMs = parseFloat((performance.now() - startTime).toFixed(2));
    console.error(`[FAILURE] POST /admin/insert-data - Execution time: ${executionTimeMs}ms - Error:`, error);
    
    const isDbError = error instanceof DatabaseError;
    const statusCode = isDbError ? 400 : 500;
    const clientMessage = isDbError
      ? 'Database operation failed'
      : 'Internal Server Error or Database failure during execution';

    return sendError(
      c,
      statusCode,
      clientMessage,
      error.message || String(error)
    );
  }
});

/**
 * POST /admin/cleanup
 * Drops all user tables in the database (excluding system tables like app_users).
 */
adminRouter.post('/cleanup', requirePermission('CREATE_SCHEMA'), async (c) => {
  const startTime = performance.now();
  console.log(`[API CALL] POST /admin/cleanup - Start`);

  try {
    const config = getAppConfig(c.env);
    const dbService = new DatabaseService(config.databaseUrl);

    // Get all user tables except app_users
    const tablesResult = await dbService.execute(`
      SELECT table_name 
      FROM information_schema.tables 
      WHERE table_schema = 'public' 
        AND table_type = 'BASE TABLE' 
        AND table_name != 'app_users'
    `);

    if (tablesResult.rows.length > 0) {
      const tableNames = tablesResult.rows.map(row => `"${row.table_name}"`).join(', ');
      const dropQuery = `DROP TABLE IF EXISTS ${tableNames} CASCADE;`;
      console.log(`[LOG] Cleanup: Executing drop statement: ${dropQuery}`);
      await dbService.execute(dropQuery);
    }

    const executionTimeMs = parseFloat((performance.now() - startTime).toFixed(2));
    console.log(`[SUCCESS] POST /admin/cleanup - Execution time: ${executionTimeMs}ms`);

    return sendSuccess(
      c,
      { success: true },
      'All user tables dropped successfully',
      executionTimeMs
    );
  } catch (error: any) {
    const executionTimeMs = parseFloat((performance.now() - startTime).toFixed(2));
    console.error(`[FAILURE] POST /admin/cleanup - Execution time: ${executionTimeMs}ms - Error:`, error);
    return sendError(
      c,
      500,
      'Failed to cleanup database tables',
      error.message || String(error)
    );
  }
});

export default adminRouter;
