import { Hono } from 'hono';
import { Env, SQLRequest } from '../models/types';
import { SchemaSQLValidator, DataSQLValidator } from '../services/validator.service';
import { DatabaseService, DatabaseError } from '../services/database.service';
import { getAppConfig } from '../config/env';
import { sendSuccess, sendError } from '../utils/response';
import { PromptService, PromptType } from '../services/PromptService';
import { GeminiService } from '../services/GeminiService';
import { AppContext } from '../types/auth';
import { requireAuth } from '../middleware/auth.middleware';
import { requirePermission } from '../middleware/authorization.middleware';

const adminRouter = new Hono<AppContext>();

// Enforce JWT authentication on all admin endpoints
adminRouter.use('*', requireAuth);

/**
 * POST /admin/create-schema
 * Receives DDL SQL (CREATE/ALTER) generated by LLM, validates, and runs it on Postgres.
 */
adminRouter.post('/create-schema', requirePermission('CREATE_SCHEMA'), async (c) => {
  const startTime = performance.now();
  console.log(`[API CALL] POST /admin/create-schema - Start`);

  try {
    const body = await c.req.json<SQLRequest>().catch(() => null);

    if (!body || (!body.sql && !body.prompt)) {
      console.warn(`[VALIDATION ERROR] POST /admin/create-schema - Missing SQL or prompt in request body`);
      return sendError(c, 400, 'Invalid Request: SQL statement or prompt is required in request body');
    }

    const config = getAppConfig(c.env);
    const dbService = new DatabaseService(config.databaseUrl);
    let sqlQuery = '';

    if (body.prompt) {
      console.log(`[LOG] Prompt received for schema generation: ${body.prompt}`);
      if (!config.geminiApiKey) {
        return sendError(c, 500, 'Configuration Error: GEMINI_API_KEY is not configured on the backend.');
      }
      
      const promptService = new PromptService();
      const geminiService = new GeminiService(config.geminiApiKey, promptService);

      const context = `Database Complexity: High\nBusiness Description: AI-Powered Application Database\nTarget Database: PostgreSQL`;
      const geminiResponse = await geminiService.generate(
        PromptType.DATABASE_GENERATION,
        body.prompt,
        context
      );

      try {
        const parsed = JSON.parse(geminiResponse);
        sqlQuery = parsed.sql || geminiResponse;
      } catch (err) {
        sqlQuery = geminiResponse;
      }
    } else {
      sqlQuery = body.sql!;
    }

    console.log(`[LOG] SQL received for admin validation:\n${sqlQuery}`);

    // Validate DDL SQL query
    let validation = SchemaSQLValidator.validate(sqlQuery);
    if (!validation.isValid) {
      if (body.prompt && config.geminiApiKey) {
        console.log(`[LOG] Schema validation failed. Attempting auto-correction using sql_validation...`);
        const promptService = new PromptService();
        const geminiService = new GeminiService(config.geminiApiKey, promptService);
        
        const context = `Generated SQL:\n${sqlQuery}\n\nValidation Failure Reason:\n${validation.reason}`;
        try {
          const correctionResponse = await geminiService.generate(
            PromptType.SQL_VALIDATION,
            'Please correct the generated DDL SQL to make it comply with validation rules.',
            context
          );
          
          let correctedSql = '';
          try {
            const parsed = JSON.parse(correctionResponse);
            correctedSql = parsed.sql || correctionResponse;
          } catch (err) {
            correctedSql = correctionResponse;
          }

          const reValidation = SchemaSQLValidator.validate(correctedSql);
          if (reValidation.isValid) {
            console.log(`[LOG] Auto-correction successful!`);
            sqlQuery = correctedSql;
            validation = reValidation;
          } else {
            console.warn(`[VALIDATION ERROR] Auto-correction SQL still invalid: ${reValidation.reason}`);
            return sendError(c, 400, 'Invalid SQL: Auto-correction failed validator rules', reValidation.reason);
          }
        } catch (corrErr: any) {
          console.error(`[LOG] Error during SQL validation auto-correction:`, corrErr);
          return sendError(c, 400, 'Invalid SQL: Command rejected by validator rules', validation.reason);
        }
      } else {
        console.warn(`[VALIDATION ERROR] POST /admin/create-schema - Blocked SQL: ${validation.reason}`);
        return sendError(c, 400, 'Invalid SQL: Command rejected by validator rules', validation.reason);
      }
    }

    // Execute schema modification SQL
    console.log(`[LOG] Executing admin SQL on Neon database...`);
    const dbResult = await dbService.execute(sqlQuery);

    const executionTimeMs = parseFloat((performance.now() - startTime).toFixed(2));
    console.log(`[SUCCESS] POST /admin/create-schema - Execution time: ${executionTimeMs}ms`);

    return sendSuccess(
      c,
      { affectedRows: dbResult.rowCount },
      'Schema operation executed successfully',
      executionTimeMs
    );
  } catch (error: any) {
    const executionTimeMs = parseFloat((performance.now() - startTime).toFixed(2));
    console.error(`[FAILURE] POST /admin/create-schema - Execution time: ${executionTimeMs}ms - Error:`, error);
    
    const isDbError = error instanceof DatabaseError;
    const statusCode = isDbError ? 400 : 500;
    const clientMessage = isDbError
      ? 'Database operation failed'
      : 'Internal Server Error or Database failure during execution';

    return sendError(
      c,
      statusCode,
      clientMessage,
      error.message || String(error)
    );
  }
});

/**
 * POST /admin/insert-data
 * Receives DML SQL (INSERT/UPDATE/DELETE) generated by LLM, validates, and runs it on Postgres.
 */
adminRouter.post('/insert-data', requirePermission('INSERT_DATA'), async (c) => {
  const startTime = performance.now();
  console.log(`[API CALL] POST /admin/insert-data - Start`);

  try {
    const body = await c.req.json<SQLRequest>().catch(() => null);

    if (!body || !body.sql) {
      console.warn(`[VALIDATION ERROR] POST /admin/insert-data - Missing SQL in request body`);
      return sendError(c, 400, 'Invalid Request: SQL statement is required in request body');
    }

    const sqlQuery = body.sql;
    console.log(`[LOG] SQL received for admin data validation:\n${sqlQuery}`);

    // Validate DML SQL query
    const validation = DataSQLValidator.validate(sqlQuery);
    if (!validation.isValid) {
      console.warn(`[VALIDATION ERROR] POST /admin/insert-data - Blocked SQL: ${validation.reason}`);
      return sendError(c, 400, 'Invalid SQL: Command rejected by validator rules', validation.reason);
    }

    // Connect to database
    const config = getAppConfig(c.env);
    const dbService = new DatabaseService(config.databaseUrl);

    // Execute data initialization SQL
    console.log(`[LOG] Executing admin data SQL on Neon database...`);
    const dbResult = await dbService.execute(sqlQuery);

    const executionTimeMs = parseFloat((performance.now() - startTime).toFixed(2));
    console.log(`[SUCCESS] POST /admin/insert-data - Execution time: ${executionTimeMs}ms`);

    return sendSuccess(
      c,
      { affectedRows: dbResult.rowCount },
      'Data operation executed successfully',
      executionTimeMs
    );
  } catch (error: any) {
    const executionTimeMs = parseFloat((performance.now() - startTime).toFixed(2));
    console.error(`[FAILURE] POST /admin/insert-data - Execution time: ${executionTimeMs}ms - Error:`, error);
    
    const isDbError = error instanceof DatabaseError;
    const statusCode = isDbError ? 400 : 500;
    const clientMessage = isDbError
      ? 'Database operation failed'
      : 'Internal Server Error or Database failure during execution';

    return sendError(
      c,
      statusCode,
      clientMessage,
      error.message || String(error)
    );
  }
});

export default adminRouter;
