import { Hono } from 'hono';
import { Env, SQLRequest } from '../models/types';
import { UserQueryValidator } from '../services/validator.service';
import { DatabaseService, DatabaseError } from '../services/database.service';
import { getAppConfig } from '../config/env';
import { sendSuccess, sendError } from '../utils/response';
import { PromptService, PromptType } from '../services/PromptService';
import { GeminiService } from '../services/GeminiService';
import { AppContext } from '../types/auth';
import { requireAuth } from '../middleware/auth.middleware';
import { requirePermission } from '../middleware/authorization.middleware';

const queryRouter = new Hono<AppContext>();

// Enforce JWT authentication on all query routes
queryRouter.use('*', requireAuth);

/**
 * POST /query
 * Receives SELECT SQL statement, validates it is SELECT-only, runs it on Neon PostgreSQL, and returns rows as JSON.
 */
/**
 * Helper function to extract potential chart data from query result rows.
 */
function extractChartData(rows: any[]): { label: string; value: number }[] {
  if (!rows || rows.length === 0) return [];
  
  const sample = rows[0];
  let labelKey = '';
  let valueKey = '';
  
  for (const [key, value] of Object.entries(sample)) {
    if (typeof value === 'number') {
      valueKey = key;
    } else if (typeof value === 'string' && !labelKey) {
      labelKey = key;
    }
  }
  
  if (!valueKey) {
    for (const [key, value] of Object.entries(sample)) {
      if (!isNaN(Number(value)) && typeof value !== 'object') {
        valueKey = key;
        break;
      }
    }
  }
  
  if (!labelKey) {
    labelKey = Object.keys(sample)[0] || '';
  }
  
  if (labelKey && valueKey && labelKey !== valueKey) {
    return rows.slice(0, 10).map(row => ({
      label: String(row[labelKey]),
      value: Number(row[valueKey])
    }));
  }
  
  return [];
}

queryRouter.post('/', requirePermission('QUERY_DATABASE'), async (c) => {
  const startTime = performance.now();
  console.log(`[API CALL] POST /query - Start`);

  try {
    const body = await c.req.json<SQLRequest>().catch(() => null);

    if (!body || (!body.sql && !body.prompt)) {
      console.warn(`[VALIDATION ERROR] POST /query - Missing SQL or prompt in request body`);
      return sendError(c, 400, 'Invalid Request: SQL statement or prompt is required in request body');
    }

    const config = getAppConfig(c.env);
    const dbService = new DatabaseService(config.databaseUrl);
    
    let sqlQuery = '';
    let explanation = '';

    if (body.prompt) {
      console.log(`[LOG] Prompt received for query generation: ${body.prompt}`);
      if (!config.geminiApiKey) {
        return sendError(c, 500, 'Configuration Error: GEMINI_API_KEY is not configured on the backend.');
      }

      // Fetch dynamic database schema
      const schemaSummary = await dbService.getSchemaSummary();

      const promptService = new PromptService();
      const geminiService = new GeminiService(config.geminiApiKey, promptService);

      const context = `Current Database Schema:\n${schemaSummary}`;
      const geminiResponse = await geminiService.generate(
        PromptType.QUERY_GENERATION,
        body.prompt,
        context
      );

      try {
        const parsed = JSON.parse(geminiResponse);
        sqlQuery = parsed.sql || geminiResponse;
        explanation = parsed.explanation || '';
      } catch (err) {
        sqlQuery = geminiResponse;
        explanation = 'Executed dynamic query generated by Gemini.';
      }
    } else {
      sqlQuery = body.sql!;
    }

    console.log(`[LOG] SQL received for user query validation:\n${sqlQuery}`);

    // Validate SELECT-only query SQL
    let validation = UserQueryValidator.validate(sqlQuery);
    if (!validation.isValid) {
      if (body.prompt && config.geminiApiKey) {
        console.log(`[LOG] Query validation failed. Attempting auto-correction using sql_validation...`);
        const promptService = new PromptService();
        const geminiService = new GeminiService(config.geminiApiKey, promptService);
        
        const context = `Generated SQL:\n${sqlQuery}\n\nValidation Failure Reason:\n${validation.reason}`;
        try {
          const correctionResponse = await geminiService.generate(
            PromptType.SQL_VALIDATION,
            'Please correct the generated query SQL to make it comply with validation rules.',
            context
          );
          
          let correctedSql = '';
          try {
            const parsed = JSON.parse(correctionResponse);
            correctedSql = parsed.sql || correctionResponse;
          } catch (err) {
            correctedSql = correctionResponse;
          }

          const reValidation = UserQueryValidator.validate(correctedSql);
          if (reValidation.isValid) {
            console.log(`[LOG] Auto-correction successful!`);
            sqlQuery = correctedSql;
            validation = reValidation;
          } else {
            console.warn(`[VALIDATION ERROR] Auto-correction SQL still invalid: ${reValidation.reason}`);
            return sendError(c, 400, 'Invalid SQL: Auto-correction failed validator rules', reValidation.reason);
          }
        } catch (corrErr: any) {
          console.error(`[LOG] Error during SQL validation auto-correction:`, corrErr);
          return sendError(c, 400, 'Invalid SQL: Command rejected by validator rules', validation.reason);
        }
      } else {
        console.warn(`[VALIDATION ERROR] POST /query - Blocked SQL: ${validation.reason}`);
        return sendError(c, 400, 'Invalid SQL: Command rejected by validator rules', validation.reason);
      }
    }

    // Execute query
    console.log(`[LOG] Executing query on Neon database...`);
    const dbResult = await dbService.execute(sqlQuery);

    const executionTimeMs = parseFloat((performance.now() - startTime).toFixed(2));

    if (body.prompt && config.geminiApiKey) {
      console.log(`[LOG] Formatting result using result_formatter...`);
      const promptService = new PromptService();
      const geminiService = new GeminiService(config.geminiApiKey, promptService);

      const context = `Original User Question: ${body.prompt}\nExecuted SQL: ${sqlQuery}\nReturned Rows: ${JSON.stringify(dbResult.rows)}`;
      let answer = explanation || 'Query executed successfully.';
      
      try {
        answer = await geminiService.generate(
          PromptType.RESULT_FORMATTER,
          'Please present the execution results to the user.',
          context
        );
      } catch (err) {
        console.error(`[LOG] Error during result formatting:`, err);
      }

      const chartData = extractChartData(dbResult.rows);

      return sendSuccess(
        c,
        {
          answer,
          sql: sqlQuery,
          chartData
        },
        'Query executed and formatted successfully',
        executionTimeMs
      );
    } else {
      console.log(`[SUCCESS] POST /query - Retained ${dbResult.rowCount} rows - Execution time: ${executionTimeMs}ms`);
      return sendSuccess(
        c,
        dbResult.rows,
        'Query executed successfully',
        executionTimeMs
      );
    }
  } catch (error: any) {
    const executionTimeMs = parseFloat((performance.now() - startTime).toFixed(2));
    console.error(`[FAILURE] POST /query - Execution time: ${executionTimeMs}ms - Error:`, error);

    const isDbError = error instanceof DatabaseError;
    const statusCode = isDbError ? 400 : 500;
    const clientMessage = isDbError
      ? 'Database operation failed'
      : 'Internal Server Error or Database failure during execution';

    return sendError(
      c,
      statusCode,
      clientMessage,
      error.message || String(error)
    );
  }
});

export default queryRouter;
